### PR TITLE
Overall pep8 for the code examples

### PR DESCRIPTION
**Pull request by iferminm**
Checked the python syntax and code conventions for the code examples.

### CODE REVIEW

**Comment by iferminm** [comment]
Hi @tariqdaouda 

I saw you reopened this PR, it's been open for over a year now, that's why I closed it.

I fixed the conflict in `README.md`, is someone going to take care of merging it if that's an option? what's the next step?

**Comment by tariqdaouda** [comment]
Hi @iferminm,

I did not merge it because travis was saying that the python 3.5 tests were broken. Now that it's ok I will merge it.

Cheers,

**Comment by iferminm** [comment]
@tariqdaouda Oh!, good, thanks!. Cheers!. I'll see if there's anything else I can contribute with.

**Comment by tariqdaouda** [comment]
Greatly appreciated.

**Pull request merged**
