### PR TITLE
Initial arangodb 3.0 support / hack

### PR DESCRIPTION
**Pull request by srozb**

### CODE REVIEW

**Comment by tariqdaouda** [comment]
Thanks it seems that this is due to changes related to Arango V3.0. pyArango has not been tested on V3.0 yet. I need to run extensive tests before accepting any modifications, I don't what people to running on 2.x to update pyArango and suddenly have their code broken.

**Comment by srozb** [comment]
This PR might break things in 2.x arangodb, but makes it possible to connect to arangodb 3.0, select database, collection and create/fetch documents. You can execute AQL queries as well, what's probably the best way to communicate with arangodb from python for now. Creating edge documents will not work at this moment as it seems that API URL has changed for this operation in 3.0.

It's probably not a good idea to accept this PR, but maybe it'll inspire someone to tinker with pyArango and port it.

**Comment by tariqdaouda** [comment]
Ok, I've created a new branch "arangoV3" for V3.0. We can centralize all the modifications there and when it is done I'll make it the new master.

**Comment by srozb** [comment]
That's good news. I believe commit 3d297ed shouldn't break V2 compatibility and it's probably trivial to replace fd9416c with something universal as well.

After this a fix for document.py#L231 (`links()` method) that changes `self.collection.documentsURL` and POST data accoring to a new V3 API would make most of pyArango functionality work fine with V3. 

Before that you should really inform ArangoDB staff to put some kind of notice on [Official python tutorial](https://www.arangodb.com/tutorials/tutorial-python/) that pyArango is V3 incompatible at this moment.

**Comment by tariqdaouda** [comment]
Thanks, I've noticed them. I've also merged your modifications into the new branch.

**Comment by tariqdaouda** [comment]
@srozb I've updated pyArango. It should now work with V3.

**Pull request merged**
