### PR TITLE
Use full error messages for unknown collection type

### PR DESCRIPTION
**Pull request by dothebart**
When misusing db.createCollection() the error message is meaningless to a novice user. improve this.

### CODE REVIEW

**Comment by dothebart** [comment]
hm, for some reason this contains more than it should. Please cherrypick only my last commits

[ 5f48fdf692df11dbcc173e9a536df5972c154ab1 , 2041860fceab100f931bf51b21aad12ac6486c09, f52c004ab711110a2e8a941b764d9c75b2a43c2e ]

sorry for causing inconvenience.

**Comment by dothebart** [comment]
I've also changed everything according to http://python-future.org/compatible_idioms.html - only the travis tests fail to pick the authentication values; which fails for me locally too. @brennv may hopefully better know how to fix this other than editing tests.js and putting the credentials in there? ;-)

**Comment by brennv** [comment]
I think we need to remove everything that relies on tests being executed as a main process so that tests.py looks like this:

https://github.com/brennv/pyArango/blob/db9f435aa911789cc574effd10c35a86595edda8/pyArango/tests/tests.py

I'll reopen this PR.

**Comment by dothebart** [comment]
@brennv what would be the manual way to invoke the tests?

Btw, I've tried in tests.py:

    if __name__ == "__main__" :
    ...
        import figleaf
       figleaf.start()

        unittest.main(exit=False)
        print("stopping!")
        figleaf.stop()
    
        figleaf.write_coverage('/tmp/.figleaf')

and generate the results:

    figleaf2html -d ~/public_html/figleaf-output/ /tmp/.figleaf

(only works with python 2.7.8 for me... )
But gives a good picture which tests areproperly covered. Some itsy bitsy remaints are there, plus errors aren't tested in most cases.

**Comment by brennv** [comment]
Right now I'm running tests with `python -m unittest discover pyArango/tests/`

**Comment by tariqdaouda** [comment]
Me too. You can also just call `python tests.py`.

**Pull request closed without merging**
