### PR TITLE
fixed 'requests (new session for request)', 'grequests (basic auth, jwt auto reset, send with max retries)'.

### PR DESCRIPTION
**Pull request by dilipvamsi**
Hi @tariqdaouda @dothebart ,
I have added the functionality. Please check for changes

Regards,
Dilip Vamsi.

### CODE REVIEW

**Comment by dothebart** [comment]
Hi, 
I think you could add that to a disconnect of the connection? The best behaviour of a broken connection is to throw anyways, so the user can decide how to handle the error - i.e. make sure that his last query wasn't executed, but only the result didn't arive - this can't be decided in the driver.

**Comment by dilipvamsi** [comment]
Hi @dothebart  @tariqdaouda ,
I have added functionality to maintain the connection even when the db server restarts or the token is expired.
It also tries to retry to max number of times provided.

But, the tests seems to failing as the travis CI is unable to setup the arangodb.
It seems that the url to retrieve the arangodb setup file in '.travis.yml' file needs to updated.
I tried to update to the latest. But it seems that is also not valid.

Thanks and Regards,
Dilip Vamsi.

**Comment by tariqdaouda** [comment]
Hi @dilipvamsi, 

Thanks for your contribution, can you check why the why the checks have faild?

**Comment by dilipvamsi** [comment]
Hi @tariqdaouda ,
The path to which the travis-ci gets the arangodb is failing to retrieve the file to install it for running the tests.
So, I was asking for your help to fix that in my previous comment.

Thanks,
Dilip Vamsi.

**Comment by tariqdaouda** [comment]
The problem seems to be coming form the ArangoDB repo. I've changed the link on the master branch to their master branch (instead of a specific branch) but it still fails.

```
$ curl -s -L https://raw.githubusercontent.com/brennv/arangodb-travis/master/setup_arangodb.sh -o setup_arangodb.sh
before_install.4
0.00s$ chmod +x setup_arangodb.sh
2.64s$ ./setup_arangodb.sh
curl -s -L http://www.arangodb.org/repositories/travisCI/ArangoDB-3.3.1.tar.gz -o ArangoDB-3.3.1.tar.gz
tar zxf ArangoDB-3.3.1.tar.gz
tar (child): ArangoDB-3.3.1.tar.gz: Cannot open: No such file or directory
```

There seem to be a problem in the link inside `setup_arangodb.sh` for downloading the db.
@dothebart do you have any idea as to why this is happening?

Cheers,

**Comment by dothebart** [comment]
Hi, 
we should switch travisci to use docker, I don't know whether I will have time to look into this.

**Comment by dilipvamsi** [comment]
Hi @tariqdaouda ,
All the coverage tests are running. 
So, check it once and merge to the current branch.
Later merge it to the main branch.

Regards,
Dilip Vamsi.

**Comment by dilipvamsi** [comment]
Hi @tariqdaouda ,
Added functions **"fetch_element"**, **"fetch_list"**, **"fetch_list_as_branches"**, **"no_fetch_run"**.
Which calls db AQLQuery and also checks the returned result size and raises appropriate **errors.

**"fetch_element"** Query result should only return list with one element.
**"fetch_list"** merges all the batches returned from the Query to a list.
**"fetch_list_as_branches"** is a generator function which yields each branch returned by Query.
**"no_fetch_run"** Query result should only return empty list.

Regards,
Dilip Vamsi.

**Comment by dothebart** [comment]
Ok, I've prepared the switch to docker based travis-ci via `dothebart:travis-with-docker-containers` - once this is merged, you should pull that into your pr, after that travis should work again.

**Comment by dilipvamsi** [comment]
Hi @tariqdaouda ,
Any plans on merging this to the master.

**Comment by dothebart** [comment]
I think we need to have a way to run the tests gevent based before the geevent branch can be merged.

**Comment by tariqdaouda** [comment]
No a bad idea. For now, it is merged to dev.

**Comment by dilipvamsi** [comment]
Hi @dothebart , @tariqdaouda ,
I have fixed the leakage issue which is caused by using the same session for multiple requests (which can lead in to returning one requests results to another)
So, I don't think it is required to use grequests at all (as session object is different for different requests).
grequests also does the same internally which creates a new session for each request.
Regards, 
Dilip Vamsi

**Comment by dothebart** [comment]
ok, can you cherry-pick dd72e5f6c540e5e148943d615ddf7553bb78ce0b ?  (my changes to the travis control?) this should make the tests run then - hopefully green ;-)

**Pull request merged**
